-- SkillBridge AI: production product-intelligence tables.
-- Applied to the live Supabase project on 2026-09-05.
create table if not exists public.saved_opportunities (
  student_id uuid not null references public.profiles(id) on delete cascade,
  internship_id bigint not null references public.internships(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (student_id, internship_id)
);
create table if not exists public.skill_assessments (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  role_id bigint references public.job_roles(id) on delete set null,
  readiness_score integer not null check (readiness_score between 0 and 100),
  skill_fit integer not null check (skill_fit between 0 and 100),
  proficiency integer not null check (proficiency between 0 and 100),
  snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create table if not exists public.activity_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  event_type text not null,
  entity_type text,
  entity_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  body text,
  type text not null default 'info',
  read_at timestamptz,
  created_at timestamptz not null default now()
);
