"use client";
import { useRouter } from "next/navigation";
import { useStudent } from "@/components/StudentState";
import { ROLES } from "@/lib/student-intelligence";
import { ArrowRight, Check, UserRound } from "lucide-react";
import { FormEvent, useState } from "react";

export default function Onboarding(){
 const {profile,setProfile,addActivity}=useStudent(); const router=useRouter(); const [step,setStep]=useState(1); const [role,setRole]=useState(profile.targetRole||"");
 function finish(e:FormEvent<HTMLFormElement>){e.preventDefault(); const f=new FormData(e.currentTarget); setProfile(p=>({...p,name:String(f.get("name")||""),course:String(f.get("course")||""),department:String(f.get("department")||""),targetRole:role,location:String(f.get("location")||""),onboardingComplete:true})); addActivity("profile","Completed student setup"); router.push("/skills")}
 return <main className="onboardingPage"><div className="onboardingBrand"><span>S</span><b>SkillBridge AI</b></div><div className="onboardingCard"><div className="onboardingProgress"><i className={step>=1?"done":""}/><i className={step>=2?"done":""}/></div>{step===1?<><div className="focusEyebrow">STEP 1 OF 2</div><h1>What are you aiming for?</h1><p>Choose one target role. SkillBridge will calculate gaps and recommendations against this role, and you can change it later.</p><div className="roleGrid">{ROLES.map(r=><button type="button" key={r.id} className={role===r.name?"selected":""} onClick={()=>setRole(r.name)}><div><b>{r.name}</b><small>{r.description}</small></div>{role===r.name&&<Check size={17}/>}</button>)}</div><button type="button" className="onboardingNext" disabled={!role} onClick={()=>setStep(2)}>Continue <ArrowRight size={17}/></button></>:<form onSubmit={finish}><div className="focusEyebrow">STEP 2 OF 2</div><h1>Build your real profile.</h1><p>No skills or proof will be invented. Your passport starts empty after setup.</p><div className="onboardingFields"><label>Name<input name="name" defaultValue={profile.name} placeholder="Your name" required/></label><label>Course<input name="course" defaultValue={profile.course} placeholder="e.g. B.Tech" required/></label><label>Department<input name="department" defaultValue={profile.department} placeholder="e.g. Computer Science Engineering" required/></label><label>Preferred location <span>optional</span><input name="location" defaultValue={profile.location} placeholder="e.g. Delhi NCR"/></label></div><div className="onboardingSelected"><UserRound size={17}/><span>Target role</span><b>{role}</b></div><button className="onboardingNext">Create my Skill Passport <ArrowRight size={17}/></button><button type="button" className="backLink" onClick={()=>setStep(1)}>← Change target role</button></form>}</div></main>
}
