"use client";
import Link from "next/link";
import { ProductShell } from "@/components/ProductShell";
import { useStudent } from "@/components/StudentState";
import { ROLES,getRole,roleReadiness,gapsForRole,roleFitRows,roleAlternatives,roleEvidenceCoverage,projectedReadinessAfterSkill } from "@/lib/student-intelligence";
import { ArrowRight, Check, Circle, Route, ShieldCheck, Target, TrendingUp, X } from "lucide-react";
import { useMemo, useState } from "react";

export default function Career(){
 const {skills,profile,setProfile,startedSteps,startStep,completedSteps,completeStep,addActivity}=useStudent();
 const [choose,setChoose]=useState(false);const [compare,setCompare]=useState(false);
 const role=getRole(profile.targetRole);const readiness=roleReadiness(skills,role);const evidence=roleEvidenceCoverage(skills,role);const gaps=gapsForRole(skills,role);const rows=roleFitRows(skills,role);const alternatives=useMemo(()=>roleAlternatives(skills),[skills]);
 const top=gaps.slice(0,5);
 function selectRole(name:string){setProfile(p=>({...p,targetRole:name}));addActivity("career",`Changed target role to ${name}`);setChoose(false)}
 return <ProductShell role="student" live={false}><section className="focusPage careerV3">
 {!profile.onboardingComplete?<div className="emptyJourney"><Target size={28}/><span>CAREER GRAPH</span><h1>Choose a target before we calculate readiness.</h1><p>SkillBridge will not assign a dream job to you. Pick one target, then the graph will explain exactly what stands between your current passport and that role.</p><Link className="heroAction" href="/onboarding">Choose my target <ArrowRight size={17}/></Link></div>:<>
  <div className="careerTopline"><div><div className="focusEyebrow">ROLE INTELLIGENCE</div><button className="roleChangeLink" onClick={()=>setChoose(true)}>TARGET ROLE · CHANGE</button><h1>{role?.name}</h1><p className="focusLead">{role?.description}</p></div><div className="careerSignalStack"><div><span>READINESS</span><b>{readiness}%</b><small>from current skills</small></div><div><span>EVIDENCE</span><b>{evidence}%</b><small>proof strength for role</small></div></div></div>
  <div className="careerTruth"><ShieldCheck size={17}/><p><b>The score is deterministic.</b> SkillBridge compares your saved skill levels against this role's configured thresholds. Evidence is shown separately so a self-rating is never silently treated as verified proof.</p></div>
  <div className="careerWorkspace"><section className="roleMap"><div className="sectionHeader"><div><span>ROLE SKILL MAP</span><h2>What the role asks for vs. what you currently have.</h2></div><button className="ghostAction" onClick={()=>setCompare(true)}><TrendingUp size={14}/> Compare careers</button></div>{rows.map(r=><div className="roleSkillRow" key={r.name}><div className="roleSkillMeta"><b>{r.name}</b><small>{r.proof}% evidence confidence</small></div><div className="dualTrack"><div className="targetTrack" style={{width:`${r.target}%`}}/><div className="currentTrack" style={{width:`${r.current}%`}}/></div><div className="roleSkillNums"><b>{r.current}%</b><small>target {r.target}</small></div></div>)}{!rows.length&&<div className="skillEmpty"><Target size={25}/><b>No role map yet.</b><p>Select a target role.</p></div>}</section>
  <aside className="gapPriority"><span>HIGHEST-LEVERAGE GAP</span>{gaps[0]?<><strong>{gaps[0].name}</strong><div className="gapNumber">-{gaps[0].gap}</div><p>Closing this gap gives the strongest immediate lift relative to the role threshold.</p>{gaps[0]&&<div className="projectionBadge">Projected readiness <b>{readiness}% → {projectedReadinessAfterSkill(skills,role,gaps[0].name,gaps[0].target)}%</b></div>}<Link href={`/skills?skill=${encodeURIComponent(gaps[0].name)}`}>Open {gaps[0].name} <ArrowRight size={14}/></Link></>:<><strong>{skills.length?"Role thresholds covered":"Passport empty"}</strong><p>{skills.length?"Now strengthen proof and evaluate opportunities.":"Add your first real skill before SkillBridge creates a meaningful priority."}</p><Link href="/skills">Open Skill Passport <ArrowRight size={14}/></Link></>}</aside></div>
  <div className="pathHeader startupPathHeader"><div><Route size={18}/><span><b>Shortest skill path</b><small>Generated from live gaps. Each action is connected to your passport.</small></span></div><Link href="/assessment">Take a quick assessment →</Link></div>
  {top.length?<div className="careerPath startupCareerPath">{top.map((g,i)=>{const id=`${role?.id}-${g.name}`;const started=startedSteps.includes(id),completed=completedSteps.includes(id);return <div className={`pathStep ${i===0?"now":"next"}`} key={g.name}><div className="pathMarker">{completed?<Check size={15}/>:started?<ArrowRight size={16}/>:<Circle size={14}/>}</div><div className="pathCopy"><span>0{i+1}</span><b>{g.name}</b><small>{g.current}% → target {g.target}%</small></div><em>{g.gap} point gap · projected {projectedReadinessAfterSkill(skills,role,g.name,g.target)}%</em><div className="pathActions"><button type="button" onClick={()=>{startStep(id);addActivity("roadmap",`Started ${g.name} roadmap step`)}}>{started||completed?"In progress":"Start"}</button><Link href={`/skills?skill=${encodeURIComponent(g.name)}`}>Open skill</Link>{started&&!completed&&<button type="button" className="completeBtn" onClick={()=>{completeStep(id);addActivity("roadmap",`Marked ${g.name} roadmap step complete`)}}>Mark done</button>}</div></div>})}</div>:<div className="skillEmpty"><Check size={28}/><b>{skills.length?"No configured skill gaps":"No path yet"}</b><p>{skills.length?"Your current levels meet this prototype role map.":"Add skills first. The roadmap is generated from actual gaps."}</p></div>}
  {choose&&<div className="modalBackdrop"><div className="roleModal startupRoleModal"><div className="modalTop"><div><span className="focusEyebrow">CHANGE TARGET</span><h3>Pick the career you want SkillBridge to optimize for.</h3></div><button className="sheetClose" onClick={()=>setChoose(false)}><X size={16}/></button></div><div className="roleGrid roleGridModal">{ROLES.map(r=><button key={r.id} className={r.name===role?.name?"selected":""} onClick={()=>selectRole(r.name)}><div><b>{r.name}</b><small>{r.description}</small></div>{r.name===role?.name&&<Check size={16}/>}</button>)}</div></div></div>}
  {compare&&<div className="modalBackdrop"><div className="roleModal compareModal"><div className="modalTop"><div><span className="focusEyebrow">CAREER FIT COMPARISON</span><h3>Your same passport across every role.</h3><p>No personality quiz. No AI guess. Just your current skills against each configured role map.</p></div><button className="sheetClose" onClick={()=>setCompare(false)}><X size={16}/></button></div><div className="careerCompareList">{alternatives.map((a,i)=><button key={a.role.id} onClick={()=>{selectRole(a.role.name);setCompare(false)}}><span>0{i+1}</span><div><b>{a.role.name}</b><small>{a.role.description}</small></div><strong>{a.readiness}%</strong><em>{a.evidence}% evidence</em></button>)}</div></div></div>}
 </>}
 </section></ProductShell>
}
