"use client";
import { useMemo,useState } from "react";
import Link from "next/link";
import { ProductShell } from "@/components/ProductShell";
import { useStudent } from "@/components/StudentState";
import { getRole,gapsForRole,roleReadiness,roleEvidenceCoverage } from "@/lib/student-intelligence";
import { ArrowRight, ArrowUp, BadgeCheck, BrainCircuit, CalendarDays, Search, ShieldCheck, Sparkles, Target } from "lucide-react";

export default function Mentor(){
 const {skills,profile}=useStudent();const role=getRole(profile.targetRole);const readiness=roleReadiness(skills,role);const evidence=roleEvidenceCoverage(skills,role);const gaps=gapsForRole(skills,role);
 const starters=useMemo(()=>[
  {icon:Target,label:"Explain my readiness",prompt:`Explain why my ${role?.name||"selected role"} readiness is ${readiness}%. Use only my current gaps and tell me the single best next action.`},
  {icon:CalendarDays,label:"Plan the next 7 days",prompt:"Create a realistic 7-day plan from my current skill gaps. Give me one proof-of-work outcome by the end."},
  {icon:Search,label:"Prepare for an internship",prompt:"Based on my current Skill Passport, what should I verify before applying to an internship and what gap should I be ready to explain?"},
 ],[role?.name,readiness]);
 const[q,setQ]=useState("");const[loading,setLoading]=useState(false);const[messages,setMessages]=useState<{who:"ai"|"me";text:string}[]>([{who:"ai",text:"I read the same target role, readiness and skill gaps as the rest of SkillBridge. I can explain or plan around them, but I cannot secretly change your official scores."}]);
 async function ask(text=q){if(!text.trim()||loading)return;setMessages(m=>[...m,{who:"me",text}]);setQ("");setLoading(true);try{const r=await fetch("/api/ai/mentor",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({role:role?.name||"No target role selected",readiness,gaps:gaps.map(g=>({name:g.name,have:g.current,need:g.target,gap:g.gap})),question:text})});const d=await r.json();setMessages(m=>[...m,{who:"ai",text:d.text||"I could not generate a response, but your deterministic scores are unchanged."}])}catch{setMessages(m=>[...m,{who:"ai",text:"I could not reach the AI service right now. Your stored profile and deterministic scores are still unchanged."}])}setLoading(false)}
 return <ProductShell role="student" live={false}><section className="mentorV3"><aside className="mentorContext"><div><span className="focusEyebrow">LIVE CONTEXT</span><h2>What Mentor knows.</h2><p>Nothing hidden. This is the structured context sent with your question.</p></div><div className="contextStat"><Target size={16}/><span><small>TARGET</small><b>{role?.name||"Not selected"}</b></span></div><div className="contextStat"><BrainCircuit size={16}/><span><small>READINESS</small><b>{readiness}% deterministic</b></span></div><div className="contextStat"><ShieldCheck size={16}/><span><small>EVIDENCE</small><b>{evidence}% role coverage</b></span></div><div className="contextGapList"><small>TOP GAPS</small>{gaps.slice(0,4).map(g=><div key={g.name}><span>{g.name}</span><b>{g.current}% → {g.target}%</b></div>)}{!gaps.length&&<p>No active configured gaps.</p>}</div><Link href="/career" className="contextLink">Open career graph <ArrowRight size={14}/></Link><div className="mentorPrivacy"><BadgeCheck size={15}/><p>The LLM explains your saved context. It does not own your score.</p></div></aside><main className="mentorStage"><header className="mentorStageHead"><div className="mentorIdentityV3"><span><Sparkles size={18}/></span><div><b>SkillBridge Mentor</b><small>Career copilot grounded in your live skill graph</small></div></div><div className="groundedPill">GROUNDED MODE</div></header><div className="mentorConversation startupConversation">{messages.map((m,i)=><div className={`chatRow ${m.who}`} key={i}>{m.who==="ai"&&<span className="aiMini"><Sparkles size={13}/></span>}<div>{m.text}</div></div>)}{loading&&<div className="chatRow ai"><span className="aiMini"><Sparkles size={13}/></span><div className="thinking">Reading your current career graph<span>•••</span></div></div>}</div><div className="mentorComposer"><div className="mentorStarters startupStarters">{starters.map(({icon:Icon,label,prompt})=><button onClick={()=>ask(prompt)} key={label}><Icon size={14}/>{label}</button>)}</div><div className="mentorInput startupMentorInput"><textarea rows={2} value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();ask()}}} placeholder="Ask something specific about your skills, roadmap, opportunity or interview…"/><button onClick={()=>ask()} disabled={loading}><ArrowUp size={18}/></button></div><small>Enter to send · Shift+Enter for a new line · Scores remain deterministic</small></div></main></section></ProductShell>
}
