"use client";
import { ProductShell } from "@/components/ProductShell";
import { useStudent, Skill, Evidence } from "@/components/StudentState";
import { BadgeCheck, BookOpenCheck, ChevronRight, FileUp, Link2, Plus, ShieldCheck, Trash2, X } from "lucide-react";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";

const status=(n:number)=>n>=75?"Confident":n>=35?"Developing":"Learning";
const tone=(n:number)=>n>=75?"strong":n>=35?"mid":"low";
export default function SkillsPage(){
 const {skills,setSkills,addActivity}=useStudent(); const params=useSearchParams(); const [selectedId,setSelectedId]=useState<string|null>(null); const [add,setAdd]=useState(false); const [prefill,setPrefill]=useState(""); const [addProof,setAddProof]=useState(false);
 const selected=skills.find(s=>s.id===selectedId)||null;
 useEffect(()=>{const name=params.get("skill");if(name){const found=skills.find(s=>s.name.toLowerCase()===name.toLowerCase());if(found)setSelectedId(found.id);else{setPrefill(name);setAdd(true)}}},[params,skills]);
 const evidenceCount=useMemo(()=>skills.reduce((a,s)=>a+s.evidence.length,0),[skills]);
 const withProof=useMemo(()=>skills.filter(s=>s.evidence.length).length,[skills]);
 function addSkill(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const name=String(f.get("name")||"").trim();const level=Math.max(0,Math.min(100,Number(f.get("level")||0)));if(!name)return;const found=skills.find(s=>s.name.toLowerCase()===name.toLowerCase());if(found){setSkills(x=>x.map(s=>s.id===found.id?{...s,level}:s));setSelectedId(found.id)}else{const s:Skill={id:`${name.toLowerCase().replace(/[^a-z0-9]+/g,"-")}-${Date.now()}`,name,level,evidence:[]};setSkills(x=>[...x,s]);setSelectedId(s.id)}addActivity("skill",`Added or updated ${name} at ${level}%`);setPrefill("");setAdd(false);e.currentTarget.reset()}
 function updateLevel(level:number){if(!selected)return;setSkills(x=>x.map(s=>s.id===selected.id?{...s,level}:s))}
 function addEvidence(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;const f=new FormData(e.currentTarget),title=String(f.get("title")||"").trim(),url=String(f.get("url")||"").trim(),type=String(f.get("type")||"Project") as Evidence["type"];if(!title)return;const item:Evidence={id:String(Date.now()),title,type,url:url||undefined,addedAt:new Date().toISOString()};setSkills(x=>x.map(s=>s.id===selected.id?{...s,evidence:[...s.evidence,item]}:s));addActivity("evidence",`Added ${type.toLowerCase()} proof for ${selected.name}`);setAddProof(false);e.currentTarget.reset()}
 return <ProductShell role="student" live={false}><section className="focusPage skillsPage">
  <div className="focusEyebrow">LIVING SKILL PASSPORT</div><div className="focusTitleRow"><div><h1>Only skills you add belong here.</h1><p className="focusLead">Start empty. Add what you have actually learned, rate your current level, then attach proof when you have it.</p></div><button className="softAction" onClick={()=>setAdd(true)}><Plus size={15}/> Add learned skill</button></div>
  <div className="passportSummary"><div><BadgeCheck size={19}/><span><b>{withProof} skills with proof</b><small>{evidenceCount} evidence item{evidenceCount===1?"":"s"} added by you</small></span></div><div><ShieldCheck size={19}/><span><b>{skills.length} skills in your passport</b><small>No sample skill is counted unless you add it</small></span></div></div>
  <div className="skillsSectionHead"><div><b>Your skills</b><small>Open any skill to change level or manage proof.</small></div></div>
  {skills.length?<div className="skillPassportList">{skills.map(s=><button className="passportSkill" key={s.id} onClick={()=>setSelectedId(s.id)}><div className={`skillOrb ${tone(s.level)}`}>{s.name.slice(0,2)}</div><div className="passportSkillMain"><div><b>{s.name}</b><span className={`skillState ${tone(s.level)}`}>{status(s.level)}</span></div><div className="passportBar"><i style={{width:`${s.level}%`}}/></div><small>{s.level}% self-rated proficiency · {s.evidence.length} proof{s.evidence.length===1?"":"s"}</small></div><ChevronRight size={18}/></button>)}</div>:<div className="skillEmpty"><BookOpenCheck size={28}/><b>Your Skill Passport is empty.</b><p>Add the first skill you have genuinely learned. It will start with zero proofs.</p><button className="softAction" onClick={()=>setAdd(true)}><Plus size={15}/> Add first skill</button></div>}
  <div className="singleCTA"><FileUp size={18}/><div><b>Evidence is optional and user-created.</b><p>Projects, repositories and certificates appear only after you add them.</p></div></div>
  {selected&&<div className="sheetBackdrop" onMouseDown={e=>{if(e.currentTarget===e.target)setSelectedId(null)}}><aside className="skillSheet"><div className="sheetTop"><div><span className="focusEyebrow">SKILL DETAIL</span><h2>{selected.name}</h2></div><button className="sheetClose" onClick={()=>setSelectedId(null)}><X size={17}/></button></div><div className="skillLevelCard"><div className="skillLevelTop"><b>Your current level</b><strong>{selected.level}%</strong></div><input className="skillRange" type="range" min="0" max="100" value={selected.level} onChange={e=>updateLevel(Number(e.target.value))}/><div className="rangeLabels"><span>Starting</span><span>Developing</span><span>Confident</span></div><p>This is your self-rating. Proof remains separate so SkillBridge never treats a slider as verified evidence.</p></div><div className="evidenceHead"><div><b>Your evidence</b><small>{selected.evidence.length} item{selected.evidence.length===1?"":"s"}</small></div><button className="softAction" onClick={()=>setAddProof(true)}><Plus size={14}/> Add proof</button></div>{selected.evidence.length?<div className="evidenceList">{selected.evidence.map(ev=><div className="evidenceItem" key={ev.id}><div className="evidenceIcon"><BadgeCheck size={15}/></div><div><b>{ev.title}</b><small>{ev.type}</small></div>{ev.url&&<a className="evidenceLink" href={ev.url} target="_blank"><Link2 size={14}/></a>}<button className="evidenceDelete" onClick={()=>setSkills(x=>x.map(s=>s.id===selected.id?{...s,evidence:s.evidence.filter(v=>v.id!==ev.id)}:s))}><Trash2 size={14}/></button></div>)}</div>:<div className="evidenceEmpty"><BadgeCheck size={21}/><b>No proof added yet.</b><p>That is okay. SkillBridge will not invent one.</p></div>}<div className="sheetDanger"><button onClick={()=>{setSkills(x=>x.filter(s=>s.id!==selected.id));setSelectedId(null)}}><Trash2 size={14}/> Remove skill from passport</button></div></aside></div>}
  {add&&<div className="modalBackdrop"><form className="miniModal" onSubmit={addSkill}><div className="modalTop"><h3>Add a learned skill</h3><button type="button" className="sheetClose" onClick={()=>{setAdd(false);setPrefill("")}}><X size={16}/></button></div><label>Skill name<input className="input" name="name" defaultValue={prefill} placeholder="e.g. Python" required/></label><label>Current level (0–100)<input className="input" name="level" type="number" min="0" max="100" defaultValue="0"/></label><p className="formHint">This creates the skill with <b>0 proofs</b>. You can add evidence later.</p><button className="primaryModalAction"><Plus size={15}/> Add to passport</button></form></div>}
  {addProof&&selected&&<div className="modalBackdrop"><form className="miniModal" onSubmit={addEvidence}><div className="modalTop"><h3>Add proof for {selected.name}</h3><button type="button" className="sheetClose" onClick={()=>setAddProof(false)}><X size={16}/></button></div><label>Proof type<select className="input" name="type"><option>Project</option><option>Certificate</option><option>Repository</option><option>Assessment</option><option>Other</option></select></label><label>Title<input className="input" name="title" placeholder="e.g. Portfolio website" required/></label><label>Link (optional)<input className="input" name="url" placeholder="https://..."/></label><button className="primaryModalAction"><Plus size={15}/> Save proof</button></form></div>}
 </section></ProductShell>
}
