"use client";
import { ProductShell } from "@/components/ProductShell";
import { useStudent } from "@/components/StudentState";
import { OPPORTUNITIES,opportunityReasons,opportunityScoreBreakdown } from "@/lib/student-intelligence";
import { Bookmark, Check, ChevronRight, Filter, Search, Sparkles, X } from "lucide-react";
import { useMemo, useState } from "react";

export default function Explore(){
 const {skills,profile,saved,toggleSaved,applied,apply,addActivity}=useStudent();
 const [tab,setTab]=useState<"all"|"saved"|"applied">("all");const [q,setQ]=useState("");const [mode,setMode]=useState("Any");const [selected,setSelected]=useState<string|null>(null);
 const all=useMemo(()=>OPPORTUNITIES.map(o=>({...o,breakdown:opportunityScoreBreakdown(skills,profile,o),reason:opportunityReasons(skills,o)})).sort((a,b)=>b.breakdown.total-a.breakdown.total),[skills,profile]);
 const rows=all.filter(o=>(tab==="all"||tab==="saved"&&saved.includes(o.id)||tab==="applied"&&applied.includes(o.id))).filter(o=>!q||`${o.role} ${o.company}`.toLowerCase().includes(q.toLowerCase())).filter(o=>mode==="Any"||o.mode===mode);const detail=all.find(r=>r.id===selected);
 return <ProductShell role="student" live={false}><section className="focusPage exploreV3">
  <div className="exploreHero"><div><div className="focusEyebrow">OPPORTUNITY INTELLIGENCE</div><h1>Don't just see a job. See your odds—and the reason.</h1><p className="focusLead">Every percentage below is recalculated from the Skill Passport you created. These listings are sample data for the SIH prototype, clearly labeled as such.</p></div><div className="sampleStamp">SAMPLE MARKET<br/><b>LIVE SCORING</b></div></div>
  <div className="exploreControls startupExploreControls"><div className="exploreTabs"><button className={tab==="all"?"active":""} onClick={()=>setTab("all")}>For you</button><button className={tab==="saved"?"active":""} onClick={()=>setTab("saved")}>Saved ({saved.length})</button><button className={tab==="applied"?"active":""} onClick={()=>setTab("applied")}>Applied ({applied.length})</button></div><div className="exploreSearch"><Search size={14}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search sample roles…"/></div><div className="modeFilter"><Filter size={13}/><select value={mode} onChange={e=>setMode(e.target.value)}><option>Any</option><option>Remote</option><option>Hybrid</option><option>On-site</option></select></div></div>
  {!skills.length&&<div className="zeroTruth"><Sparkles size={18}/><div><b>Your passport has no skills, so every match is 0%.</b><p>Add a skill and return here—the exact same listings will recalculate immediately.</p></div></div>}
  <div className="opportunityStack">{rows.map((o,i)=><article className="opportunityCardV3" key={o.id}><div className="opRank">0{i+1}</div><div className="opMain"><div className="opTags"><span>SAMPLE LISTING</span><em>{o.mode}</em></div><h2>{o.role}</h2><p>{o.company} · {o.loc} · {o.stipend}</p><div className="opReasonLine">{o.breakdown.total>0?(o.reason.good[0]||o.reason.gap):"No skill evidence in your passport yet."}</div></div><div className="opScore"><strong>{o.breakdown.total}%</strong><small>YOUR MATCH</small></div><div className="opActions"><button className={saved.includes(o.id)?"saveBtn active":"saveBtn"} onClick={()=>{toggleSaved(o.id);addActivity("opportunity",`${saved.includes(o.id)?"Removed":"Saved"} ${o.role}`)}}><Bookmark size={15}/></button><button className="inspectBtn" onClick={()=>setSelected(o.id)}>Explain match <ChevronRight size={15}/></button></div></article>)}</div>
  {!rows.length&&<div className="skillEmpty"><Search size={24}/><b>No opportunities in this view.</b><p>Try another filter or save/apply to a sample listing first.</p></div>}
  {detail&&<div className="sheetBackdrop" onMouseDown={e=>{if(e.currentTarget===e.target)setSelected(null)}}><aside className="skillSheet opportunitySheet startupOpportunitySheet"><div className="sheetTop"><div><span className="focusEyebrow">EXPLAINABLE MATCH</span><h2>{detail.role}</h2><p>{detail.company} · {detail.loc}</p></div><button className="sheetClose" onClick={()=>setSelected(null)}><X size={17}/></button></div><div className="matchHero"><div><strong>{detail.breakdown.total}%</strong><small>deterministic match</small></div><p>{detail.reason.gap}</p></div><div className="matchFormula"><b>Why this number?</b><p>We expose the same five factors used by the prototype ranking engine.</p>{[["Skill fit",detail.breakdown.skillFit,45],["Proficiency",detail.breakdown.proficiency,20],["Role interest",detail.breakdown.roleInterest,15],["Availability",detail.breakdown.availability,10],["Learning readiness",detail.breakdown.learningReadiness,10]].map(([label,value,weight]:any)=><div className="factorRow" key={label}><span>{label}<small>{weight}% weight</small></span><div><i style={{width:`${value}%`}}/></div><b>{value}%</b></div>)}</div><div className="matchReasons"><div><b>What already helps</b>{detail.reason.good.length?detail.reason.good.map(x=><p key={x}><Check size={13}/> {x}</p>):<p>No configured requirement is fully met yet.</p>}</div><div><b>What is holding you back</b>{detail.reason.gaps.length?detail.reason.gaps.map(g=><p key={g.name}><span>−{g.target-g.current}</span> {g.name}: {g.current}% / {g.target}%</p>):<p>No configured gap detected.</p>}</div></div><div className="requiredSkills"><b>Role requirements</b>{Object.entries(detail.requirements).map(([n,t])=><div key={n}><span>{n}</span><em>target {t}%</em></div>)}</div><div className="sheetActions"><button onClick={()=>toggleSaved(detail.id)}><Bookmark size={15}/>{saved.includes(detail.id)?"Remove saved":"Save"}</button><button className="primaryModalAction" disabled={applied.includes(detail.id)} onClick={()=>{apply(detail.id);addActivity("application",`Applied to ${detail.role} sample listing`)}}>{applied.includes(detail.id)?"Applied in prototype":"Apply in prototype"}</button></div></aside></div>}
 </section></ProductShell>
}
