"use client";
import Link from "next/link";
import { ProductShell } from "@/components/ProductShell";
import { useStudent } from "@/components/StudentState";
import { getRole,gapsForRole,roleReadiness,roleEvidenceCoverage,OPPORTUNITIES,opportunityScore,nextBestAction } from "@/lib/student-intelligence";
import { ArrowRight, BadgeCheck, BriefcaseBusiness, Compass, ShieldCheck, Sparkles, Target, UserRound } from "lucide-react";

export default function Dashboard(){
 const {skills,profile,activity}=useStudent();
 const role=getRole(profile.targetRole);const readiness=roleReadiness(skills,role);const proof=roleEvidenceCoverage(skills,role);const gaps=gapsForRole(skills,role);const action=nextBestAction(skills,profile);
 const ranked=OPPORTUNITIES.map(o=>({o,score:opportunityScore(skills,profile,o)})).sort((a,b)=>b.score-a.score);const best=ranked[0];
 const proofCount=skills.reduce((a,s)=>a+s.evidence.length,0);
 return <ProductShell role="student" live={false}><section className="focusPage startupHome">
  {!profile.onboardingComplete?<div className="emptyJourney startupEmpty"><div className="signalOrb"><Compass size={28}/></div><span>YOUR CAREER OS STARTS EMPTY</span><h1>No fake score. No fake skills. Start with you.</h1><p>Choose a target role, then add only the skills and evidence you actually have. Every score, roadmap and opportunity will derive from that single profile.</p><Link href="/onboarding" className="heroAction">Create my career graph <ArrowRight size={17}/></Link></div>:<>
  <div className="homeCommand"><div className="homeCommandCopy"><div className="focusEyebrow">CAREER COMMAND CENTER</div><p className="focusHello">{profile.name ? `Hi, ${profile.name}.` : "Your career signal."}</p><h1>{action.title}</h1><p className="focusLead">{action.body}</p><div className="homeCommandActions"><Link className="heroAction" href={action.href}>Do this next <ArrowRight size={16}/></Link><Link className="ghostAction" href="/mentor"><Sparkles size={15}/> Ask Mentor why</Link></div></div><div className="signalScore"><span className="signalScoreLabel">READINESS</span><strong>{readiness}<sup>%</sup></strong><small>{role?.name||"No target"}</small><div className="signalScoreTrack"><i style={{width:`${readiness}%`}}/></div></div></div>
  <div className="signalRail"><Link href="/skills"><BadgeCheck size={17}/><span><small>SKILL PASSPORT</small><b>{skills.length} skills · {proofCount} proof</b></span><ArrowRight size={15}/></Link><Link href="/career"><Target size={17}/><span><small>ACTIVE GAPS</small><b>{gaps.length?`${gaps.length} to close`:"No configured gap"}</b></span><ArrowRight size={15}/></Link><Link href="/skills"><ShieldCheck size={17}/><span><small>EVIDENCE SIGNAL</small><b>{proof}% role evidence</b></span><ArrowRight size={15}/></Link><Link href="/explore"><BriefcaseBusiness size={17}/><span><small>BEST SAMPLE MATCH</small><b>{best?`${best.score}% · ${best.o.role}`:"No match yet"}</b></span><ArrowRight size={15}/></Link></div>
  <div className="homeDecisionGrid"><article className="decisionCard primaryDecision"><span>WHY THIS IS YOUR NEXT MOVE</span><h2>{gaps[0]?`${gaps[0].name} has the largest relative gap.`:"Your next action is derived from your live profile."}</h2><p>{gaps[0]?`Current ${gaps[0].current}% · role target ${gaps[0].target}% · gap ${gaps[0].gap} points. Change the skill and this recommendation changes too.`:"SkillBridge does not use a hidden chatbot score. The recommendation comes from structured role requirements and your saved state."}</p><Link href="/career">Open the explanation <ArrowRight size={15}/></Link></article><article className="decisionCard"><span>OPPORTUNITY SIGNAL</span><h2>{best&&best.score>0?`${best.o.role} is currently your strongest sample fit.`:"No opportunity has earned a match yet."}</h2><p>{best&&best.score>0?`${best.score}% based on skill fit, proficiency, role interest, availability and learning readiness.`:"Add real skills first. Opportunity scores stay at zero when your passport is empty."}</p><Link href="/explore">Inspect the match <ArrowRight size={15}/></Link></article></div>
  <div className="activityLine"><span>RECENT SIGNAL</span><b>{activity[0]?.label||"No actions yet. Your real activity will appear here."}</b><small>{activity[0]?new Date(activity[0].at).toLocaleString():""}</small></div>
  </>}
 </section></ProductShell>
}
